### ISSUE TITLE
Bridgetown v1.0.0 and bridgetown-quick-search v1.1.2 - load error

### ISSUE THREAD

**Issue by btihen** [bridgetownrb/bridgetown-quick-search#12]
Error:

```bash
bin/bridgetown start

[Frontend] esbuild: frontend bundling started...
[Frontend]  > node_modules/bridgetown-quick-search/frontend/javascript/index.js:22:0: error: Unexpected "@"
[Frontend]     22 │ @customElement("bridgetown-search-form")
[Frontend]        ╵ ^
[Frontend] 
[Frontend] esbuild: build process error, cannot write manifest
[Frontend] error Command failed with exit code 1.
[Frontend] info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
[Frontend]   Exception raised: RuntimeError
[Frontend] Command failed with status (1): [yarn run esbuild-dev...] 
[Frontend]                  1: /Users/btihen/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/gems/rake-13.0.6/lib/rake/file_utils.rb:67:in `block in create_shell_runner'
[Frontend]                  2: /Users/btihen/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/gems/rake-13.0.6/lib/rake/file_utils.rb:57:in `sh'
[Frontend]                  3: /Users/btihen/Dropbox/devel/marpori/learning/ruby_kafi/bridgetown_talk/ruby_kafi_bridgetown_default_code/Rakefile:35:in `block (2 levels) in <top (required)>'
[Frontend]                  4: /Users/btihen/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/gems/rake-13.0.6/lib/rake/task.rb:281:in `block in execute'
[Frontend]                  5: /Users/btihen/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/gems/rake-13.0.6/lib/rake/task.rb:281:in `each'
[Frontend]          Backtrace: Use the --trace option for complete information.
```

Reproduce with:
```bash
bridgetown new bridgetown_search_crash
cd bridgetown_search_crash
bundle add bridgetown-quick-search -g bridgetown_plugins

# follow instructions in README
# add import to; `frontend/javascript/index.js`
import "bridgetown-quick-search/dist"
# add the Liquid component to `src/_components/navbar.liquid`
{% render "bridgetown_quick_search/search" %}

# start bridgetown:
bin/bridgetown start

# see above error report
```

**Comment by jaredcwhite** [comment]
@btihen I followed your steps but was unable to reproduce the error. Are you sure you included "/dist" at the end of the import in your project?
